server.port=${PORT:8080}
logging.level.org.atmosphere=warn

vaadin.launch-browser=false
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.fitradar

backend.base-url=${BACKEND_BASE_URL:http://localhost:8081}